config/routes.rb
ThirstyHipster::Application.routes.draw do
  root to: 'locations#index'
  devise_for :users
  resources :locations do
    resources :comments
  end
  resources :comments
  resources :searches
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_reader :display_address, :latitude, :longitude

  geocoded_by :street_address
  before_create :geocode

  validates_presence_of :name, :address, :city, :state, :start_time, :end_time, :description
  validates :name, :uniqueness => {:scope => :city}
  validate :days_were_selected

  has_many :comments
  has_many :users, through: :comments

  def street_address
    [address, city, state, 'US'].compact.join(', ')
  end

  def day_sequence(location)
  	sequence = []
  	if sunday && monday && tuesday && wednesday && thursday && friday && saturday
  		sequence << "Sunday - Saturday"
  	elsif monday && tuesday && wednesday && thursday && friday
  		sequence << "Monday - Friday"
  	else
  		if sunday
  			sequence << "Sunday"
  		end
  		if monday
  			sequence << "Monday"
  		end
			if tuesday
				sequence << "Tuesday"
			end
			if wednesday
				sequence << "Wednesday"
			end
			if thursday
				sequence << "Thursday"
			end
			if friday
				sequence << "Friday"
			end
			if saturday
				sequence << "Saturday"
			end
  	end
  	sequence.join(", ")
  end

  private

  def days_were_selected
    days = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']
    checked = false
    days.each do |day|
      checked = true if self[day].present?
    end
    if checked == false
      self.errors.add(:days, "- You must select at least one day.")
    end
  end
end

app/models/search.rb
class Search
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :locations, through: :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new
    @location = Location.find(params[:location_id])
    @comment = @location.comments.new
  end

  def create
    @location =Location.find(params[:location_id])
    @comment = Comment.create!(comment_params)
    respond_to do |format|
      format.html { redirect_to location_path(@location) }
      format.js
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @location = Location.find(params[:location_id])
    @comment = Comment.find(params[:id])
    @comment.update_attributes(comment_params)
    respond_to do |format|
      format.html { redirect_to location_path(@location) }
      format.js
    end
  end

  def destroy
    @location = Location.find(params[:location_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to location_path(@location) }
      format.js
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :user_id, :location_id)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    # @ip = request.ip
    @ip = '97201'
    zip = params[:zip] ? params[:zip] : @ip
    @zip = zip
    if params[:date]
      time = params[:date]
      time = Time.new(time["year"], time["month"], time["day"], time["hour"], time["minute"])
    else
      time = Time.now
    end

    # @locations = Location.all
    @location_results = Location.where(["zip = :zip and start_time >= :time", { zip: zip, time: time }])
    @locations = @location_results.map { |r| r.attributes }
  end

  def new
    @location = Location.new
  end

  def create
    params[:location].parse_time_select! :start_time
    params[:location].parse_time_select! :end_time

    @location = Location.new(location_params)
    if @location.save
      flash[:notice]="New location created."
      redirect_to location_path(@location)
    else
      render 'new'
    end
  end

  def show
    @location = Location.find(params[:id])
    @comment = Comment.new
    @sequence = @location.day_sequence(@location)
    respond_to do |format|
      format.html
      format.js { render 'show.html.erb' }
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    params[:location].parse_time_select! :start_time
    params[:location].parse_time_select! :end_time

    @location = Location.find(params[:id])
    if @location.update(location_params)
      flash[:notice]="Location updated."
      redirect_to location_path(@location)
    else
      render 'edit'
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    flash[:notice] = "Location has been removed."
    redirect_to locations_path
  end

private

  def location_params
    params.require(:location).permit(
      :name, :address, :city, :state, :zip, :phone, :display_address,
      :start_time, :end_time, :description, :url,
      :sunday, :monday, :tuesday, :wednesday,
      :thursday, :friday, :saturday, :latitude, :longitude
    )
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
    @search = Search.new
  end

  def new
    @search = Search.new
  end

  def create
    @search = Search.new
    if params[:name] == "" || params[:city] == ""
      flash[:alert] = "Please enter a valid name and city or zip."
    end
    gateway = ::FetchLocations.new
    response = gateway.process_request(params[:name], params[:city])
    @response = gateway.process_response(response)
    render 'index'
  end

  def show
    @search = Search.find(params[:id])
  end

private
  def search_params
    params.require(:search).permit(:address, :city, :state, :zip, :phone, :display_address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <%= comment.comment %>
  <%= link_to "update", edit_location_comment_path(@location, comment), :class => "btn-xs btn-warning" %>
  <%= link_to "delete", location_comment_path(@location, comment), :class => "btn-xs btn-danger", method: :delete %>
</div>

app/views/comments/_form.html.erb
<%= form_for [@comment.location, @comment], remote: request.xhr? do |f|%>
  <%= f.label :comment %>
  <%= f.text_field :comment %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :location_id, :value => @comment.location.id %>
  <%= f.submit %>
<% end %>

app/views/comments/_show.html.erb
<%= comment.comment %>

 <%= link_to "update", edit_location_comment_path, :class => "btn-xs btn-warning" %>

 <%= link_to "delete", location_comment_path, :class => "btn-xs btn-danger", method: :delete %>

app/views/comments/create.js.erb
$('#new_comment').hide();
$('#new_link').show();
$('#review_list').append('<li><%= j render('comment', comment: @comment) %></li>');

app/views/comments/edit.html.erb
<h1>Edit comment</h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<%= render('form') %>

app/views/comments/new.js.erb
$('#new_link').hide().after('<%= j render "form" %>' )

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %>| The Thirsty Hipster </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

<!-- ***************GOOGLE API TEST************* -->

<style type="text/css">
  html { height: 100% }
  body { height: 100%; margin: 0; padding: 0 }
</style>
<script type="text/javascript"
  key=ENV['API_KEY']
  src="https://maps.googleapis.com/maps/api/js?key&sensor=false">
</script>
<script type="text/javascript">

  function initialize() {

    var locations = <%= raw @locations.to_json %>;
    var infoWindowContent = [];
    var startHour, startMin

    for (var i = 0; i < locations.length; i++) {
      startHour = locations[i].start_time.substr(11, 2);
      startMin = locations[i].start_time.substr(14, 2);
      startHour < 12 ? startHour = startHour : startHour = startHour - 12;

      var startTime = startHour + ':' + startMin;

      endHour = locations[i].end_time.substr(11, 2);
      endMin = locations[i].end_time.substr(14, 2);
      endHour < 12 ? endHour = endHour : endHour = endHour - 12;

      var endTime = endHour + ':' + endMin;

      var item =
        [
          '<div>' +
            '<h3>' + locations[i].name + '</h3>' +
              '<p>' + locations[i].address + ', ' + locations[i].city + ', ' + locations[i].state + ' ' + locations[0].zip + '</p>' +
              '<p>' + 'Happy hour: ' + startTime + '-' + endTime + '</p>' +
              '<p>' + locations[i].description + '</p>' +
          '</div>'
        ];
      infoWindowContent.push(item);
    };

    var map = new google.maps.Map(document.getElementById('map-canvas'), {
      zoom: 14,
      // we need to update the center to the center point of the zip added
      center: new google.maps.LatLng(locations[0].latitude, locations[0].longitude),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var infoWindow = new google.maps.InfoWindow(), marker, i;

    for (i = 0; i < locations.length; i++) {
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i].latitude, locations[i].longitude),
        map: map,
        title: locations[i].name
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
          return function() {
              infoWindow.setContent(infoWindowContent[i][0]);
              infoWindow.open(map, marker);
          }
      })(marker, i));
    };
  }

</script>

<!-- ****************************************** -->

</head>
<body onload="initialize()" >
  <div class="container">
    <div class="row">
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/locations"><b>thirstyhipster</b></a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
<!--               <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
              </form> -->
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Add location", new_search_path %></li>
              <% if !user_signed_in? %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Sign in", new_user_session_path %></li>
              <% end %>

              <% if user_signed_in? %>
              <li><%= link_to "Add Location", searches_path %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                  </ul>
                </li>
              <% end %>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    </div>

  <div class = "container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = yield(:title)
      | The Thirsty Hipster
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %script{:src => "https://maps.googleapis.com/maps/api/js?ENV['API_KEY']", :type => "text/javascript"}
  %body{:onload => "initialize()"}
    .container
      .row
        %nav.navbar.navbar-inverse{:role => "navigation"}
          .container-fluid
            / Brand and toggle get grouped for better mobile display
            .navbar-header
              %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
                %span.sr-only Toggle navigation
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar
              %a.navbar-brand{:href => "/locations"}
                %b thirstyhipster
            / Collect the nav links, forms, and other content for toggling
            #bs-example-navbar-collapse-1.collapse.navbar-collapse
              %ul.nav.navbar-nav
                %form.navbar-form.navbar-left{:role => "search"}
                  = form_tag("/locations", method: "get") do
                    .form-group
                      .form-control
                        = label_tag :zip, "Zip:"
                        = text_field_tag :zip, @zip
                    .form-group
                      .form-control
                        = label_tag :start_time, "Time:"
                        = select_time(Time.now + 30.minutes, :minute_step => 30, :ampm => true, start_hour: 12, end_hour: 23)
                    %button.btn.btn-default{:type => "submit"} Submit
              %ul.nav.navbar-nav.navbar-right
                %li= link_to "Add location", new_search_path
                - if !user_signed_in?
                  %li= link_to "Sign up", new_user_registration_path
                  %li= link_to "Sign in", new_user_session_path

                %li.dropdown
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                    = current_user.email
                    %b.caret
                  %ul.dropdown-menu
                    %li= link_to 'Edit profile', edit_user_registration_path
                    %li.divider
                    %li= link_to "Logout", destroy_user_session_path, method: :delete
            / /.navbar-collapse
          / /.container-fluid
      .container
        - if flash[:notice]
          .alert.alert-success
            = flash[:notice]
        - elsif flash[:alert]
          .alert.alert-danger
            = flash[:alert]
        = yield

app/views/locations/_form.html.erb
<%= render 'layouts/errors', :object => @location %>
<%= form_for @location do |f| %>

  <div class="form_group">
    <%=f.label :name, "Name*" %> <br>
    <%=f.text_field :name, :value => params[:name], :required => true%>
  </div><br>

  <div class="form_group">
    <%=f.label :description, "What are the Happy Hour specials?*" %> <br>
    <%=f.text_area :description, :rows=>5, :cols=>40, :required => true%>
  </div> <br>

  <div class="form_group">
    <h5><strong>Which days have a Happy Hour?*</strong></h5>
    <%= f.check_box :sunday %>
    <%=f.label :sunday, "Sunday" %>
    <%= f.check_box :monday %>
    <%=f.label :monday, "Monday" %>
    <%= f.check_box :tuesday %>
    <%=f.label :tuesday, "Tuesday" %>
    <%= f.check_box :wednesday %>
    <%=f.label :wednesday, "Wednesday" %>
    <%= f.check_box :thursday %>
    <%=f.label :thursday, "Thursday" %>
    <%= f.check_box :friday %>
    <%=f.label :friday, "Friday" %>
    <%= f.check_box :saturday %>
    <%=f.label :saturday, "Saturday" %>
  </div> <br>

  <div class="form_group">
    <%=f.label :start_time, "Happy Hour Starting Time*" %> <br>
    <%= f.time_select :start_time,
      :labels => false,
      :combined => true,
      :default => Time.now.change(:hour => 15, :min => 00),
      :minute_interval => 30,
      :time_separator => "",
      :start_hour => 12,
      :start_minute => 00,
      :end_hour => 23,
      :end_minute => 00,
      :ampm => true,
      :required => true
    %>
  </div> <br>

  <div class="form_group">
    <%=f.label :end_time, "Happy Hour Ending Time*" %> <br>
    <%= f.time_select :end_time,
      :labels => false,
      :combined => true,
      :default => Time.now.change(:hour => 17, :min => 00),
      :minute_interval => 30,
      :time_separator => "",
      :start_hour => 12,
      :start_minute => 00,
      :end_hour => 23,
      :end_minute => 00,
      :ampm => true,
      :required => true
    %>
  </div> <br>

  <div class="form_group">
    <%=f.label :address, "Address*" %> <br>
    <%=f.text_field :address, :value => params[:address], :required => true %>
  </div> <br>

  <div class="form_group">
    <%=f.label :city, "City*" %> <br>
    <%=f.text_field :city, :value => params[:city], :required => true %>
  </div> <br>

  <div class="form_group">
    <%=f.label :state, "State*" %> <br>
    <%=f.text_field :state, :value => params[:state], :required => true %>
  </div> <br>

  <div class="form_group">
    <%=f.label :zip, "Zipcode*" %> <br>
    <%=f.text_field :zip, :value => params[:zip], :required => true %>
  </div> <br>

  <%= f.text_field :display_address, :type => :hidden, :value => params[:display_address] %>

  <div class="form_group">
    <%=f.label :phone, "Phone" %> <br>
    <%=f.text_field :phone, :value => params[:phone] %>
  </div> <br>

  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/locations/edit.html.erb
<h1>Edit <%= @location.name %></h1>

<%= render 'layouts/errors', :object => @location %>
<%= form_for @location do |f| %>

  <div class="form_group">
    <%=f.label :name, "Name" %> <br>
    <%=f.text_field :name %>
  </div><br>

  <div class="form_group">
    <%=f.label :description, "Description" %> <br>
    <%=f.text_area :description %>
  </div> <br>

  <div class="form_group">
    <%=f.label :address, "Street Address" %> <br>
    <%=f.text_field :address %>
  </div> <br>

  <div class="form_group">
    <%=f.label :city, "City" %> <br>
    <%=f.text_field :city %>
  </div> <br>

  <div class="form_group">
    <%=f.label :state, "State" %> <br>
    <%=f.text_field :state %>
  </div> <br>

  <div class="form_group">
    <%=f.label :zip, "Zipcode" %> <br>
    <%=f.text_field :zip %>
  </div> <br>

  <div class="form_group">
    <h5><strong>Which days have a Happy Hour?</strong></h5>
    <%=f.label :sunday, "Sunday" %>
    <%= f.check_box :sunday %>
    <%=f.label :monday, "Monday" %>
    <%= f.check_box :monday %>
    <%=f.label :tuesday, "Tuesday" %>
    <%= f.check_box :tuesday %>
    <%=f.label :wednesday, "Wednesday" %>
    <%= f.check_box :wednesday %>
    <%=f.label :thursday, "Thursday" %>
    <%= f.check_box :thursday %>
    <%=f.label :friday, "Friday" %>
    <%= f.check_box :friday %>
    <%=f.label :saturday, "Saturday" %>
    <%= f.check_box :saturday %>
  </div> <br>

  <div class="form_group">
    <%=f.label :start_time, "Happy Hour Starting Time" %> <br>
    <%= f.time_select :start_time,
      :labels => false,
      :combined => true,
      :default => Time.now.change(:hour => 15, :min => 00),
      :minute_interval => 30,
      :time_separator => "",
      :start_hour => 12,
      :start_minute => 00,
      :end_hour => 23,
      :end_minute => 00,
      :ampm => true
    %>
  </div> <br>

  <div class="form_group">
    <%=f.label :end_time, "Happy Hour Ending Time" %> <br>
    <%= f.time_select :end_time,
      :labels => false,
      :combined => true,
      :default => Time.now.change(:hour => 15, :min => 00),
      :minute_interval => 30,
      :time_separator => "",
      :start_hour => 12,
      :start_minute => 00,
      :end_hour => 23,
      :end_minute => 00,
      :ampm => true
    %>
  </div> <br>

  <div class="form_group">
    <%=f.label :phone, "Phone" %> <br>
    <%=f.text_field :phone %>
  </div> <br>

  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/locations/index.html.erb
<div class="row">

	<div class="col-md-6">
			<h2>Search for Local Happy Hours</h2>
			<h5><em>Thirsty Hipster helps you find the best local happy hours based on users recommendation. Search current listings or add and review new ones.</em></h5>
			<%= form_tag("/locations", method: "get") do %>
			  <div class="form_group">
			    <%= label_tag :zip, "Near Zipcode: " %><br>
			    <%= text_field_tag :zip, @zip %>
			  </div>
			  <span style="font-size: 85%">Seeded zips: 97201, 97205, 97209, 97214, 97232</span>
			  <br><br>
			  <div class="form_group">
			    <%= label_tag :start_time, "Starting Around" %> <br>
			    <%= select_time(Time.now + 30.minutes, :minute_step => 30, :ampm => true, start_hour: 12, end_hour: 23) %>
			  </div> <br>
			  <%= submit_tag "Search", :class => "btn btn-primary" %>
			<% end %> <br>
		<div id="map-canvas"></div>
	</div>

  <div class="col-md-4 col-md-offset-1">
  	<% if @locations.length > 0 %>
			<h2>Happy Hours</h2>
				<% @location_results.each do |location| %>
					<h3><%= link_to "#{location.name}", location_path(location) %></h3>
					<p><%= location.city %>, <%= location.state %> <%= location.zip %></p>
				<% end %>
		<% elsif params[:zip] %>
			<h2>Happy Hours</h2>
			<h5 id="no-locations"><em>Sorry, no happy hours have been added for this zip code. <%= link_to "Click here", searches_path %> to add a location.<em></h5>
		<% end %>
	</div>
</div>

app/views/locations/index.html.haml
.row{:onload => "initialize()"}
  .col-xs-8
    %h2 Search for Local Happy Hours
    %h5
      %em Thirsty Hipster helps you find the best local happy hours based on users recommendation. Search current listings or add and review new ones.
  #map-canvas
  .col-xs-4
    .panel.panel-default.panel-transparent
      .panel-body
        - if @results.length > 0
          %h2 Happy Hours
          - @results.each do |result|
            %h3.location-title= link_to "#{result.name}", location_path(result)
            %div= result.address
            %div= "#{result.city}, #{result.state} #{result.zip}"
        - elsif params[:zip]
          %h2 Happy Hours
          %h5#no-results
            %em
              Sorry, no happy hours have been added for this zip code. #{link_to "Click here", searches_path} to add a location.
:javascript
  var pins = #{@pins.to_json}

app/views/locations/new.html.erb
<h1><%= params[:name] %></h1>

<%= render 'locations/form' %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>
<p>Address: <strong><%= @location.address %></strong></p>
<p>City: <strong><%= @location.city %></strong></p>
<p>State: <strong><%= @location.state %></strong></p>
<p>Zip: <strong><%= @location.zip %></strong></p>
<p>Phone: <strong><%= @location.phone %></strong></p>
<p>LatLong: <%= "#{@location['latitude']} #{@location['longitude']}"%></p>

<p>Days: <%= @sequence %>
<p>Happy Hour: <strong><%= @location.start_time.to_s(:quick) %></strong> to <strong><%= @location.end_time.to_s(:quick) %></strong></p>
<p>Happy Hour Specials:</p>
<p class="tab"><%= @location.description %></p>

<%= link_to "Edit", edit_location_path, class: "btn btn-primary" %>
<%= link_to "Delete", location_path, method: "delete", class: "btn btn-danger" %>

<hr>

<% if current_user == nil %>
  <p><em>Must be logged in to leave a comment.</em></p>
<% end %>

<p><%= link_to "New Comment", new_location_comment_path(@location), id: "new_link", remote: true %></p>

<div id="comments">
  <h3>Comments</h3>
  <ul class="list-unstyled" id="review_list">
    <%= render @location.comments %>
  </ul>
</div>

app/views/searches/_form.html.erb
<%= form_tag searches_path do %>
  <div class="form_group">
    <%= label_tag :name, "Name*" %><br>
    <%= text_field_tag :name, nil, :required => true %>
  </div><br>
  <div class="form_group">
    <%= label_tag(:city, "City or Zip*") %><br>
    <%= text_field_tag(:city, "Portland", :required => true ) %>
  </div><br>
  <%= submit_tag "Search", :class => "btn btn-primary" %>
<% end %>

app/views/searches/index.html.erb
<div class="row">
  <div class="col-md-5">
    <h1>Add a Happy Hour</h1>
    <p>Search for local bars by entering their zip code. Then, update the entry with information about its happy hour. If you don't find your bar, you can create an entry from scratch.
    <%= render 'form' %>
  </div>

  <div class="col-md-6 col-md-offset-1">
    <% if @response != nil %>
    <h1>Results</h1>
      <p>Select the bar you want to add to the Thirsty Hipster happy hour database</p>
      <% @response.each do |location|%>
        <h4><%= link_to "#{location.name}", new_location_path({:name => location.name, :address => location[:address], :city => location.city, :state => location.state, :zip => location.zip, :phone => location.phone, :display_address => location[:display_address]}) %></h4>
        <%= image_tag location.rating %>
        <%= location.address %>, <%= location.city %>, <%= location.state %>
      <% end %><br><br>
      <%= link_to "Add New Location if Not Listed Above", new_location_path, class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/searches/new.html.erb
<h1>Add a New Happy Hour</h1>
<div class="row">
	<div class="col-md-6">
		<p>Search for local bars by name and city or zip. Then, update the entry with information about its happy hour. If you can't find your location, you can create an entry from scratch.
		<%= render 'form' %>
	</div>
</div>

app/views/searches/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <h1>Results</h1>

  <div class="col-md-4">
    <div class="container">
      <h1>New Search</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>